<?php
// The Arabic for the parties and menus the site started with (app/menus.first.php).
//
// Used once, when the Arabic page arrives: each English text below that is still
// on the site, word for word, gets its Arabic filled in. After that the Arabic
// lives in the admin, beside the English, and this file is not read again.
//
// Like the English menus, this is a first draft for the kitchen to review.

return [
    // ------------------------------------------------------------ the parties
    'Buffet' => 'بوفيه',
    'One table' => 'مائدة واحدة',
    'everyone' => 'الجميع',
    'Family gatherings, company days' => 'لمّات العائلة، أيام الشركات',
    'Pizza party' => 'حفلة بيتزا',
    'Pizza' => 'بيتزا',
    'people' => 'صحبة',
    'Birthdays, casual evenings' => 'أعياد الميلاد، السهرات البسيطة',
    'Barbecue' => 'باربكيو',
    'Fire' => 'نار',
    'friends' => 'أصحاب',
    'Gardens, rooftops, Sahel' => 'الحدائق، الأسطح، الساحل',
    'Coffee break' => 'استراحة قهوة',
    'Coffee' => 'قهوة',
    'break' => 'استراحة',
    'Meetings and trainings' => 'الاجتماعات والتدريبات',
    'Birthday' => 'عيد ميلاد',
    'Cake' => 'تورتة',
    'candles' => 'شموع',
    'Children and milestones' => 'الأطفال والمناسبات الكبيرة',
    'Iftar' => 'إفطار',
    'Sunset' => 'غروب',
    'family' => 'عائلة',
    'Home and company iftars' => 'إفطارات البيت والشركات',
    'Taco bar' => 'تاكو بار',
    'Tacos' => 'تاكو',
    'your way' => 'على طريقتك',
    'Casual evenings, office Thursdays' => 'السهرات البسيطة، خميس المكتب',
    'Halloween' => 'هالوين',
    'Trick' => 'خدعة',
    'treat' => 'حلوى',
    "Children's parties, schools, office Thursdays" => 'حفلات الأطفال، المدارس، خميس المكتب',

    // ------------------------------------------------------------ seasons and courses
    'Autumn 2026' => 'خريف 2026',
    'Autumn and winter 2026' => 'خريف وشتاء 2026',
    'Ramadan 2027' => 'رمضان 2027',
    'All year' => 'طوال العام',
    'October 2026' => 'أكتوبر 2026',

    'To start' => 'للبداية',
    'To begin' => 'للبداية',
    'The table' => 'المائدة',
    'To finish' => 'للختام',
    'To drink' => 'للشرب',
    'From the oven' => 'من الفرن',
    'From the fire' => 'من النار',
    'On the table' => 'على المائدة',
    'Savoury' => 'حوادق',
    'Sweet' => 'حلو',
    'Small hands' => 'للأيدي الصغيرة',
    'For the grown-ups' => 'للكبار',
    'The moment' => 'اللحظة',
    'To break the fast' => 'لكسر الصيام',
    'From the grill' => 'من الشواية',
    'On the side' => 'أطباق جانبية',
    'The fillings' => 'الحشوات',
    'The bar' => 'البار',
    'First bites' => 'أول لقمة',
    'Live stations' => 'أركان الطهي المباشر',
    'Treats' => 'الحلوى',

    // ------------------------------------------------------------ Buffet: The long table
    'The long table' => 'المائدة الطويلة',
    'Egyptian cooking for a full table. Big dishes down the middle, a card on each one that says where it came from, and bread baked while you watch.'
        => 'طبخ مصري لمائدة عامرة. أطباق كبيرة في الوسط، وعلى كل طبق بطاقة تقول من أين جاء، وعيش يُخبز أمامك.',
    'Garden leaves' => 'ورقيات الحديقة',
    'Rocket, dill and coriander picked this week, baladi lemon, olive oil. Dressed at the table.'
        => 'جرجير وشبت وكزبرة من قطاف هذا الأسبوع، ليمون بلدي، زيت زيتون. تُتبَّل على المائدة.',
    'Ruby beets' => 'بنجر ياقوتي',
    'Roast beetroot, white cheese, pomegranate and mint.' => 'بنجر مشوي، جبنة بيضاء، رمان ونعناع.',
    'Burnt aubergine' => 'باذنجان مشوي على اللهب',
    'Charred whole over the flame, then tahini, cumin and lemon.' => 'يُشوى كاملاً على اللهب، ثم طحينة وكمون وليمون.',
    'Golden lentils' => 'عدس ذهبي',
    'A warm lentil soup with cumin, lemon and crisp bread.' => 'شوربة عدس دافئة بالكمون والليمون والعيش المحمّص.',
    'Bread from the fire' => 'عيش من النار',
    'Baladi bread, baked in front of your guests.' => 'عيش بلدي، يُخبز أمام ضيوفك.',
    'Lemon chicken' => 'دجاج بالليمون',
    'Our own chicken, roasted whole with lemon and garlic. Carved to order.' => 'دجاج من تربيتنا، يُشوى كاملاً بالليمون والثوم. يُقطَّع عند الطلب.',
    'Overnight beef' => 'لحم بقري مطهو طوال الليل',
    'From our butchery. Cooked low through the night with onions and bay.' => 'من جزارتنا. يُطهى على نار هادئة طوال الليل مع البصل وورق اللورا.',
    'Charcoal kofta' => 'كفتة على الفحم',
    'Minced the same day, grilled over charcoal, served on parsley and onion.' => 'تُفرم في اليوم نفسه، تُشوى على الفحم، وتُقدَّم على بقدونس وبصل.',
    'Smoked freekeh' => 'فريك مدخّن',
    'Green wheat with roast pumpkin and toasted nuts. A main for guests who skip the meat.'
        => 'فريك مع قرع عسلي مشوي ومكسرات محمّصة. طبق رئيسي لمن لا يأكل اللحم.',
    'Garden torly' => 'تورلي الحديقة',
    'Autumn vegetables baked slowly in tomato, the Egyptian way.' => 'خضار الخريف تُطهى على مهل في الطماطم، على الطريقة المصرية.',
    'Golden rice' => 'أرز ذهبي',
    'Egyptian rice, toasted vermicelli, ghee.' => 'أرز مصري، شعرية محمّرة، سمن بلدي.',
    'Om Ali' => 'أم علي',
    'Pastry, milk, nuts and raisins. Served warm from the oven.' => 'رقائق عجين، لبن، مكسرات وزبيب. تُقدَّم دافئة من الفرن.',
    'The batata cart' => 'عربة البطاطا',
    'Sweet potato roasted until it caramelises, with cream and black honey.' => 'بطاطا تُشوى حتى تتكرمل، مع قشطة وعسل أسود.',
    'Fruit of the week' => 'فاكهة الأسبوع',
    'Guava, pomegranate, persimmon. Whatever is best right now.' => 'جوافة، رمان، كاكا. أفضل ما في الموسم الآن.',
    'Karkade and tamarind' => 'كركديه وتمر هندي',
    'Made in our kitchen, served cold.' => 'يُصنعان في مطبخنا، ويُقدَّمان باردين.',

    // ------------------------------------------------------------ Pizza party: Hot from the oven
    'Hot from the oven' => 'ساخنة من الفرن',
    'Our oven comes to you. Dough made that morning, stretched and baked in front of your guests. Italian classics, with our own sausage and produce from the farm.'
        => 'فرننا يأتي إليك. عجين يُصنع في الصباح نفسه، يُفرد ويُخبز أمام ضيوفك. كلاسيكيات إيطالية، بسجق من صنعنا وخضار من المزرعة.',
    'Rosemary focaccia' => 'فوكاتشا بالروزماري',
    'Baked in the pizza oven, with olive oil and sea salt.' => 'تُخبز في فرن البيتزا، بزيت الزيتون وملح البحر.',
    'Bruschetta' => 'بروسكيتا',
    'Tomato, garlic and basil on grilled bread.' => 'طماطم وثوم وريحان على عيش مشوي.',
    'Rocket salad' => 'سلطة جرجير',
    'Rocket from the farm, tomato, lemon and olive oil.' => 'جرجير من المزرعة، طماطم، ليمون وزيت زيتون.',
    'Margherita' => 'مارجريتا',
    'Tomato, mozzarella, basil.' => 'طماطم، موتزاريلا، ريحان.',
    'Marinara' => 'مارينارا',
    'Tomato, garlic, oregano and olive oil. No cheese.' => 'طماطم، ثوم، أوريجانو وزيت زيتون. بدون جبنة.',
    'Salsiccia' => 'سالسيتشا',
    'Our own sausage, roast peppers, onion.' => 'سجق من صنعنا، فلفل مشوي، بصل.',
    'Ortolana' => 'أورتولانا',
    'Aubergine, courgette and peppers from the farm, grilled first.' => 'باذنجان وكوسة وفلفل من المزرعة، تُشوى أولاً.',
    'Bianca' => 'بيانكا',
    'Mozzarella, garlic, rocket and lemon. No tomato.' => 'موتزاريلا، ثوم، جرجير وليمون. بدون طماطم.',
    'Basterma and rocket' => 'بسطرمة وجرجير',
    'Our answer to bresaola: cured beef, mozzarella, and rocket after the oven.' => 'ردّنا على البريزاولا: بسطرمة، موتزاريلا، وجرجير يُضاف بعد الفرن.',
    'Tiramisu' => 'تيراميسو',
    'Made in our kitchen the day before, the way it should be.' => 'يُصنع في مطبخنا قبلها بيوم، كما يجب.',
    'The last pizza' => 'البيتزا الأخيرة',
    'Cream and honey on hot dough, torn and shared.' => 'قشطة وعسل على عجين ساخن، تُقطَّع باليد وتُتشارك.',
    'Lemonade with mint' => 'ليمون بالنعناع',
    'Lemons, mint, a little sugar.' => 'ليمون، نعناع، قليل من السكر.',

    // ------------------------------------------------------------ Barbecue: Around the fire
    'Around the fire' => 'حول النار',
    'A charcoal grill, a grill master and meat from our own butchery. Everyone ends up standing around it.'
        => 'شواية فحم، ومعلّم شوي، ولحوم من جزارتنا. الكل ينتهي واقفاً حولها.',
    'Minced the same day with parsley and onion.' => 'تُفرم في اليوم نفسه مع البقدونس والبصل.',
    'Lamb chops' => 'ريش ضاني',
    'Salt, pepper, fire. Nothing else.' => 'ملح، فلفل، نار. ولا شيء آخر.',
    "The butcher's cut" => 'قطعة الجزار',
    'One large cut chosen by our butchery that week, grilled whole and sliced at the grill.'
        => 'قطعة كبيرة تختارها جزارتنا ذلك الأسبوع، تُشوى كاملة وتُقطَّع عند الشواية.',
    'Chicken shish' => 'شيش طاووق',
    'Our own chicken, after a night in yoghurt, lemon and garlic.' => 'دجاج من تربيتنا، بعد ليلة في الزبادي والليمون والثوم.',
    'Blistered vegetables' => 'خضار مشوية على اللهب',
    'Aubergine, peppers, onion and tomato, charred and dressed with lemon.' => 'باذنجان وفلفل وبصل وطماطم، تُشوى وتُتبَّل بالليمون.',
    'Batata in the embers' => 'بطاطا في الجمر',
    'Sweet potato cooked in the coals, split open with butter and salt.' => 'بطاطا تُطهى في الجمر، وتُفتح بالزبدة والملح.',
    'Three bowls' => 'ثلاثة أطباق',
    'Tahini, burnt aubergine, and a sharp tomato and garlic salsa.' => 'طحينة، باذنجان مشوي على اللهب، وصلصة طماطم وثوم لاذعة.',
    'Baladi salad' => 'سلطة بلدي',
    'Tomato, cucumber, onion and herbs, chopped small, with lemon.' => 'طماطم وخيار وبصل وأعشاب، مقطّعة ناعماً، مع الليمون.',
    'House pickles' => 'مخلل البيت',
    'Carrot, turnip, lemon and chilli, pickled in our kitchen.' => 'جزر ولفت وليمون وشطة، تُخلَّل في مطبخنا.',
    'Zalabia, hot' => 'زلابية ساخنة',
    'Small doughnuts fried to order, with honey or sugar.' => 'تُقلى عند الطلب، بالعسل أو السكر.',
    'Guava, pomegranate, persimmon.' => 'جوافة، رمان، كاكا.',

    // ------------------------------------------------------------ Coffee break: The good break
    'The good break' => 'الاستراحة الطيبة',
    'Food people leave their desks for. Set up before the meeting, cleared before the next one.'
        => 'طعام يترك الناس مكاتبهم من أجله. يُجهَّز قبل الاجتماع، ويُرفع قبل الاجتماع التالي.',
    'Coffee and tea' => 'قهوة وشاي',
    'Brewed on the spot.' => 'يُحضَّران في المكان.',
    'Juice of the day' => 'عصير اليوم',
    'Pressed that morning.' => 'يُعصر في الصباح نفسه.',
    'Real hot chocolate' => 'شوكولاتة ساخنة حقيقية',
    'Chocolate melted into milk. No powder.' => 'شوكولاتة مذابة في اللبن. بلا مساحيق.',
    'Eggs your way' => 'بيض على طريقتك',
    'For morning meetings. Cooked to order, with herbs or cheese.' => 'لاجتماعات الصباح. يُطهى عند الطلب، بالأعشاب أو الجبنة.',
    'Butter croissants' => 'كرواسون بالزبدة',
    'Plain or with cheese. Baked that morning.' => 'سادة أو بالجبنة. يُخبز في الصباح نفسه.',
    'Small sandwiches' => 'ساندوتشات صغيرة',
    'On our own bread: roast chicken, egg and herbs, cheese and tomato.' => 'على عيش من صنعنا: دجاج مشوي، بيض وأعشاب، جبنة وطماطم.',
    'Quiche of the week' => 'كيش الأسبوع',
    'Vegetables from the farm in a butter crust.' => 'خضار من المزرعة في عجينة بالزبدة.',
    'Cookies, still warm' => 'كوكيز ما زال دافئاً',
    'Chocolate chunk, and oat and raisin. Baked that morning and served warm.' => 'بقطع الشوكولاتة، وبالشوفان والزبيب. يُخبز في الصباح نفسه ويُقدَّم دافئاً.',
    'Sticky date cake' => 'كيكة التمر',
    'A dark, soft loaf, sliced thick.' => 'كيكة داكنة وطرية، تُقطَّع شرائح سميكة.',
    'Lemon loaf' => 'كيكة الليمون',
    'Sharp with lemon, with a thin glaze.' => 'لاذعة بالليمون، بطبقة سكر رقيقة.',
    'Morning pots' => 'أكواب الصباح',
    'Yoghurt, our own granola and fruit.' => 'زبادي، جرانولا من صنعنا، وفاكهة.',
    'Fruit cups' => 'أكواب فاكهة',
    'Cut to order.' => 'تُقطَّع عند الطلب.',

    // ------------------------------------------------------------ Birthday: Make a wish
    'Make a wish' => 'تمنَّ أمنية',
    'Food children finish and parents steal. A table for the grown-ups too, and a cake made for the day.'
        => 'طعام يُنهيه الأطفال ويخطف منه الأهل. مائدة للكبار أيضاً، وتورتة تُصنع لهذا اليوم.',
    'Mini burgers' => 'ميني برجر',
    'Beef from our butchery, soft buns baked in our kitchen.' => 'لحم بقري من جزارتنا، وعيش طري يُخبز في مطبخنا.',
    'Crispy chicken' => 'دجاج مقرمش',
    'Our own chicken, crumbed by hand.' => 'دجاج من تربيتنا، يُغطّى بالبقسماط باليد.',
    'Pizza squares' => 'مربعات بيتزا',
    'Tomato and cheese, straight from the oven.' => 'طماطم وجبنة، من الفرن مباشرة.',
    'Pasta to order' => 'مكرونة عند الطلب',
    'Tomato or white sauce, cooked in the pan while they watch.' => 'بصلصة الطماطم أو الصلصة البيضاء، تُطهى في الطاسة أمامهم.',
    'Rainbow sticks' => 'أصابع قوس قزح',
    'Carrot, cucumber and peppers with tahini and labneh.' => 'جزر وخيار وفلفل مع طحينة ولبنة.',
    'Fruit sticks' => 'أسياخ فاكهة',
    'The colourful plate that empties first.' => 'الطبق الملوّن الذي يفرغ أولاً.',
    'Rocket, herbs, lemon.' => 'جرجير، أعشاب، ليمون.',
    'Kofta rolls' => 'ساندوتشات كفتة',
    'Charcoal kofta in warm bread with tahini and pickles.' => 'كفتة على الفحم في عيش دافئ مع طحينة ومخلل.',
    'With tahini and warm bread.' => 'مع طحينة وعيش دافئ.',
    'The birthday cake' => 'تورتة عيد الميلاد',
    'Made to order. Tell us the name and the number.' => 'تُصنع عند الطلب. قل لنا الاسم والرقم.',
    'Fruit ice pops' => 'آيس بوب بالفاكهة',
    'Guava, pomegranate or karkade. Fruit, water, a little sugar.' => 'جوافة أو رمان أو كركديه. فاكهة، ماء، قليل من السكر.',

    // ------------------------------------------------------------ Iftar: When the sun sets
    'When the sun sets' => 'حين تغرب الشمس',
    'On the table before the call to prayer and served to share, the way an iftar should be.'
        => 'على المائدة قبل الأذان، ويُقدَّم للمشاركة، كما يجب أن يكون الإفطار.',
    'Dates and milk' => 'تمر ولبن',
    'Waiting at every place.' => 'في انتظار كل ضيف.',
    'Three Ramadan drinks' => 'ثلاثة مشروبات رمضانية',
    'Qamar el-din, karkade and tamarind, made in our kitchen.' => 'قمر الدين وكركديه وتمر هندي، تُصنع في مطبخنا.',
    'Sambousek' => 'سمبوسك',
    'Cheese and meat, folded by hand, fried just before sunset.' => 'بالجبنة واللحم، تُطوى باليد، وتُقلى قبل الغروب بقليل.',
    'Rocket, dill and coriander, baladi lemon, olive oil.' => 'جرجير وشبت وكزبرة، ليمون بلدي، زيت زيتون.',
    'Lamb fattah' => 'فتة ضاني',
    'Lamb from our butchery, rice, crisp bread, garlic and vinegar.' => 'ضاني من جزارتنا، أرز، عيش محمّص، ثوم وخل.',
    'Chicken with freekeh' => 'دجاج بالفريك',
    'Our own chicken, roasted and filled with smoked green wheat.' => 'دجاج من تربيتنا، يُشوى ويُحشى بالفريك المدخّن.',
    'Winter tagine' => 'طاجن الشتاء',
    'Green peas, carrots and beef in tomato, baked in clay.' => 'بسلة وجزر ولحم بقري في الطماطم، يُطهى في الفخار.',
    'Mahshi' => 'محشي',
    'Vine leaves and winter cabbage, rolled by hand.' => 'ورق عنب وكرنب الشتاء، يُلفّان باليد.',
    'Qatayef to order' => 'قطايف عند الطلب',
    'Filled with nuts or cream, fried in front of you, dipped in syrup.' => 'تُحشى بالمكسرات أو القشطة، تُقلى أمامك، وتُغمس في الشربات.',
    'Konafa' => 'كنافة',
    'With cream, still warm.' => 'بالقشطة، ما زالت دافئة.',
    'Winter fruit' => 'فاكهة الشتاء',
    'Oranges and strawberries, at their best at this time of year.' => 'برتقال وفراولة، في أفضل حالاتهما في هذا الوقت من السنة.',
    'Tea with fresh mint' => 'شاي بالنعناع الطازج',
    'And coffee, for the long evening.' => 'وقهوة، للسهرة الطويلة.',

    // ------------------------------------------------------------ Barbecue: The backyard
    'The backyard' => 'حديقة البيت',
    'American street food from our butchery: burgers, sausages and slow brisket. Paper trays, soft buns, no cutlery needed.'
        => 'أكل شارع أمريكي من جزارتنا: برجر، سجق، وبريسكت يُطهى على مهل. أطباق ورق، عيش طري، ولا حاجة لشوكة وسكين.',
    'The smash burger' => 'سماش برجر',
    'Beef from our butchery, smashed on the flat-top, with cheese, pickles and our burger sauce.'
        => 'لحم بقري من جزارتنا، يُضغط على الصاج، مع جبنة ومخلل وصوص البرجر من صنعنا.',
    'The chicken burger' => 'برجر الدجاج',
    'Our own chicken, crisp outside, with slaw in a soft bun.' => 'دجاج من تربيتنا، مقرمش من الخارج، مع كولسلو في عيش طري.',
    'Sausage in a bun' => 'سجق في عيش',
    'Our own beef sausage, grilled, with soft onions and mustard.' => 'سجق بقري من صنعنا، مشوي، مع بصل طري ومسطردة.',
    'Twelve-hour brisket' => 'بريسكت 12 ساعة',
    'Cooked low for twelve hours and sliced at the board. In a bun, or on its own.' => 'يُطهى على نار هادئة اثنتي عشرة ساعة ويُقطَّع أمامك. في عيش، أو وحده.',
    'Fries, skin on' => 'بطاطس مقلية بقشرها',
    'Cut that morning, fried to order.' => 'تُقطَّع في الصباح نفسه، وتُقلى عند الطلب.',
    'Slaw' => 'كولسلو',
    'Cabbage and carrot from the farm, in a light dressing.' => 'كرنب وجزر من المزرعة، بتتبيلة خفيفة.',
    'Corn on the cob' => 'ذرة مشوية',
    'Charred on the grill, with butter and salt.' => 'تُشوى على الشواية، بالزبدة والملح.',
    'Pickles and sauces' => 'مخلل وصوصات',
    'House pickles, burger sauce, barbecue sauce and mustard, made in our kitchen.' => 'مخلل البيت، صوص البرجر، صوص الباربكيو، ومسطردة، كلها من صنع مطبخنا.',
    'Chocolate chunk. Baked that day and served warm.' => 'بقطع الشوكولاتة. يُخبز في اليوم نفسه ويُقدَّم دافئاً.',

    // ------------------------------------------------------------ Taco bar: Build your own
    'Build your own' => 'اصنعها بنفسك',
    'Warm tortillas, fillings straight from the grill and the pan, and a bar of everything to pile on top. Guests build their own, and go back for another.'
        => 'تورتيلا دافئة، حشوات من الشواية والطاسة مباشرة، وبار فيه كل ما يوضع فوقها. كل ضيف يصنع التاكو بنفسه، ويعود لواحدة أخرى.',
    'Slow beef' => 'لحم بقري على مهل',
    'Beef from our butchery, cooked low with cumin and chilli until it pulls apart.' => 'لحم بقري من جزارتنا، يُطهى على نار هادئة بالكمون والشطة حتى يتفتّت.',
    'Charcoal chicken' => 'دجاج على الفحم',
    'Our own chicken with lime and garlic, off the grill and sliced to order.' => 'دجاج من تربيتنا باللايم والثوم، من الشواية، ويُقطَّع عند الطلب.',
    'Spiced sausage' => 'سجق متبّل',
    'Our own sausage, crumbled and crisped in the pan with paprika.' => 'سجق من صنعنا، يُفتَّت ويُحمَّر في الطاسة بالبابريكا.',
    'Charred cauliflower' => 'قرنبيط مشوي',
    'From the farm, roasted with cumin and lime. For guests who skip the meat.' => 'من المزرعة، يُشوى بالكمون واللايم. لمن لا يأكل اللحم.',
    'Warm tortillas' => 'تورتيلا دافئة',
    'Heated on the plancha as you reach the front of the line.' => 'تُسخَّن على الصاج حين يصل دورك.',
    'Fresh salsa' => 'سالسا طازجة',
    'Tomato, onion, coriander and lime, chopped that day.' => 'طماطم وبصل وكزبرة ولايم، تُقطَّع في اليوم نفسه.',
    'Guacamole' => 'جواكامولي',
    'Mashed to order.' => 'يُهرس عند الطلب.',
    'Pink onions and slaw' => 'بصل وردي وكولسلو',
    'Quick-pickled onions and a crisp cabbage slaw.' => 'بصل مخلّل سريعاً وكولسلو كرنب مقرمش.',
    'House hot sauce' => 'شطة البيت',
    'Mild, medium, and one to be careful with.' => 'خفيفة، ومتوسطة، وواحدة تحتاج إلى حذر.',
    'Corn in a cup' => 'ذرة في كوب',
    'Charred corn with lime, chilli and cheese.' => 'ذرة مشوية باللايم والشطة والجبنة.',
    'Tortilla chips' => 'تورتيلا شيبس',
    'Fried that day, with salsa.' => 'تُقلى في اليوم نفسه، مع السالسا.',
    'Churros to order' => 'تشوروس عند الطلب',
    'Fried in front of you, rolled in cinnamon sugar, with chocolate.' => 'تُقلى أمامك، وتُغطّى بالسكر والقرفة، مع الشوكولاتة.',
    'Hibiscus cooler' => 'كركديه مثلّج',
    'Mexico calls it jamaica, Egypt calls it karkade. Served cold with lime.' => 'في المكسيك اسمه خامايكا، وفي مصر اسمه كركديه. يُقدَّم بارداً مع اللايم.',

    // ------------------------------------------------------------ Halloween: The pumpkin party
    'The pumpkin party' => 'حفلة القرع',
    'A Halloween party where the colours come from the food: pumpkin, batata, karkade and beetroot. Nothing is dyed. Live stations for the children, and a table for the grown-ups too.'
        => 'حفلة هالوين ألوانها من الطعام نفسه: قرع عسلي، بطاطا، كركديه وبنجر. لا ألوان صناعية. أركان طهي مباشر للأطفال، ومائدة للكبار أيضاً.',
    'Pumpkin in a cup' => 'قرع في كوب',
    'Roast pumpkin soup with cumin and toasted seeds, served in small cups.' => 'شوربة قرع عسلي مشوي بالكمون واللب المحمّص، تُقدَّم في أكواب صغيرة.',
    'Charred whole over the flame, then tahini, cumin and lemon. With warm bread.' => 'يُشوى كاملاً على اللهب، ثم طحينة وكمون وليمون. مع عيش دافئ.',
    'Orange sticks' => 'أصابع برتقالية',
    'Carrot, peppers and cucumber with tahini and labneh.' => 'جزر وفلفل وخيار مع طحينة ولبنة.',
    'Make a face' => 'ارسم وجهاً',
    'Children top their own small pizza with a face. Baked in the oven while they watch.' => 'كل طفل يرسم وجهاً على بيتزا صغيرة. تُخبز في الفرن أمامهم.',
    'Charcoal kofta in warm bread with tahini and pickles. For the grown-ups.' => 'كفتة على الفحم في عيش دافئ مع طحينة ومخلل. للكبار.',
    'Pumpkin freekeh' => 'فريك بالقرع',
    'Smoked green wheat with roast pumpkin and toasted nuts. A main for guests who skip the meat.'
        => 'فريك مدخّن مع قرع عسلي مشوي ومكسرات محمّصة. طبق رئيسي لمن لا يأكل اللحم.',
    "Qar' asali, warm" => 'قرع عسلي دافئ',
    'The Egyptian baked pumpkin pudding, in small pots.' => 'حلوى القرع العسلي المصرية في الفرن، في أوانٍ صغيرة.',
    'The treat bar' => 'بار الحلوى',
    'Sweets made in our kitchen to fill a paper bag: sesame and peanut brittle, date and cocoa balls, popcorn.'
        => 'حلوى من صنع مطبخنا تملأ كيساً من الورق: سمسمية وفولية، كرات التمر والكاكاو، فشار.',
    'Karkade pops' => 'آيس بوب كركديه',
    'Ice pops made from karkade, fruit and a little sugar.' => 'آيس بوب من الكركديه والفاكهة وقليل من السكر.',
    'Red punch' => 'بانش أحمر',
    'Cold karkade with pomegranate seeds.' => 'كركديه بارد مع حبّات الرمان.',
];
