<?php
// The Arabic for the parties and menus the site started with (app/menus.first.php).
//
// Used once, when the Arabic page arrives: each English text below that is still
// on the site, word for word, gets its Arabic filled in. After that the Arabic
// lives in the admin, beside the English, and this file is not read again.
//
// It is Egyptian Arabic, the way people speak, not formal Arabic.
// Like the English menus, this is a first draft for the kitchen to review.

return [
    // ------------------------------------------------------------ the parties
    'Buffet' => 'بوفيه',
    'One table' => 'سفرة واحدة',
    'everyone' => 'الكل',
    'Family gatherings, company days' => 'لمّات العيلة، أيام الشركات',
    'Pizza party' => 'حفلة بيتزا',
    'Pizza' => 'بيتزا',
    'people' => 'صحبة',
    'Birthdays, casual evenings' => 'أعياد الميلاد، السهرات البسيطة',
    'Barbecue' => 'باربكيو',
    'Fire' => 'نار',
    'friends' => 'صحاب',
    'Gardens, rooftops, Sahel' => 'الجناين، الروف، الساحل',
    'Coffee break' => 'كوفي بريك',
    'Coffee' => 'قهوة',
    'break' => 'بريك',
    'Meetings and trainings' => 'الاجتماعات والتدريبات',
    'Birthday' => 'عيد ميلاد',
    'Cake' => 'تورتة',
    'candles' => 'شمع',
    'Children and milestones' => 'الأطفال والمناسبات الكبيرة',
    'Iftar' => 'فطار رمضان',
    'Sunset' => 'المغرب',
    'family' => 'العيلة',
    'Home and company iftars' => 'فطار البيت والشركات',
    'Taco bar' => 'تاكو بار',
    'Tacos' => 'تاكو',
    'your way' => 'على مزاجك',
    'Casual evenings, office Thursdays' => 'السهرات البسيطة، خميس المكتب',
    'Halloween' => 'هالوين',
    'Trick' => 'مقلب',
    'treat' => 'حلويات',
    "Children's parties, schools, office Thursdays" => 'حفلات الأطفال، المدارس، خميس المكتب',

    // ------------------------------------------------------------ seasons and courses
    'Autumn 2026' => 'خريف 2026',
    'Autumn and winter 2026' => 'خريف وشتا 2026',
    'Ramadan 2027' => 'رمضان 2027',
    'All year' => 'طول السنة',
    'October 2026' => 'أكتوبر 2026',

    'To start' => 'في الأول',
    'To begin' => 'في الأول',
    'The table' => 'السفرة',
    'To finish' => 'في الآخر',
    'To drink' => 'المشروبات',
    'From the oven' => 'من الفرن',
    'From the fire' => 'من على النار',
    'On the table' => 'على السفرة',
    'Savoury' => 'حوادق',
    'Sweet' => 'حلو',
    'Small hands' => 'للصغيرين',
    'For the grown-ups' => 'للكبار',
    'The moment' => 'اللحظة',
    'To break the fast' => 'نكسر الصيام',
    'From the grill' => 'من على الشواية',
    'On the side' => 'على الجنب',
    'The fillings' => 'الحشوات',
    'The bar' => 'البار',
    'First bites' => 'أول لقمة',
    'Live stations' => 'أركان لايف',
    'Treats' => 'الحلويات',

    // ------------------------------------------------------------ Buffet: The long table
    'The long table' => 'السفرة الطويلة',
    'Egyptian cooking for a full table. Big dishes down the middle, a card on each one that says where it came from, and bread baked while you watch.'
        => 'أكل مصري لسفرة مليانة. أطباق كبيرة في النص، وعلى كل طبق كارت بيقول جاي منين، وعيش بيتخبز قدامك.',
    'Garden leaves' => 'خضرة الجنينة',
    'Rocket, dill and coriander picked this week, baladi lemon, olive oil. Dressed at the table.'
        => 'جرجير وشبت وكزبرة مقطوفين الأسبوع ده، لمون بلدي، زيت زيتون. بنتبّلها على السفرة.',
    'Ruby beets' => 'بنجر ياقوتي',
    'Roast beetroot, white cheese, pomegranate and mint.' => 'بنجر مشوي، جبنة بيضا، رمان ونعناع.',
    'Burnt aubergine' => 'بدنجان مشوي على النار',
    'Charred whole over the flame, then tahini, cumin and lemon.' => 'بيتشوي صحيح على النار، وبعدين طحينة وكمون ولمون.',
    'Golden lentils' => 'عدس دهبي',
    'A warm lentil soup with cumin, lemon and crisp bread.' => 'شوربة عدس سخنة بالكمون واللمون والعيش المحمّص.',
    'Bread from the fire' => 'عيش من على النار',
    'Baladi bread, baked in front of your guests.' => 'عيش بلدي، بيتخبز قدام ضيوفك.',
    'Lemon chicken' => 'فراخ باللمون',
    'Our own chicken, roasted whole with lemon and garlic. Carved to order.' => 'فراخ من تربيتنا، بتتشوي صحيحة باللمون والتوم. وبتتقطّع على الطلب.',
    'Overnight beef' => 'لحمة بقري مطبوخة طول الليل',
    'From our butchery. Cooked low through the night with onions and bay.' => 'من جزارتنا. بتتسوّى على نار هادية طول الليل مع البصل وورق اللورا.',
    'Charcoal kofta' => 'كفتة على الفحم',
    'Minced the same day, grilled over charcoal, served on parsley and onion.' => 'بتتفرم في نفس اليوم، بتتشوي على الفحم، وبتتقدّم على بقدونس وبصل.',
    'Smoked freekeh' => 'فريك مدخّن',
    'Green wheat with roast pumpkin and toasted nuts. A main for guests who skip the meat.'
        => 'فريك مع قرع عسلي مشوي ومكسرات محمّصة. طبق رئيسي للي مش بياكل لحمة.',
    'Garden torly' => 'تورلي الجنينة',
    'Autumn vegetables baked slowly in tomato, the Egyptian way.' => 'خضار الخريف متسوّي على مهله في الصلصة، على الطريقة المصرية.',
    'Golden rice' => 'رز دهبي',
    'Egyptian rice, toasted vermicelli, ghee.' => 'رز مصري، شعرية محمّرة، سمن بلدي.',
    'Om Ali' => 'أم علي',
    'Pastry, milk, nuts and raisins. Served warm from the oven.' => 'رقايق عجين، لبن، مكسرات وزبيب. بتتقدّم سخنة من الفرن.',
    'The batata cart' => 'عربية البطاطا',
    'Sweet potato roasted until it caramelises, with cream and black honey.' => 'بطاطا بتتشوي لحد ما تتكرمل، مع قشطة وعسل أسود.',
    'Fruit of the week' => 'فاكهة الأسبوع',
    'Guava, pomegranate, persimmon. Whatever is best right now.' => 'جوافة، رمان، كاكا. أحسن حاجة في موسمها دلوقتي.',
    'Karkade and tamarind' => 'كركديه وتمر هندي',
    'Made in our kitchen, served cold.' => 'معمولين في مطبخنا، وبيتقدّموا ساقعين.',

    // ------------------------------------------------------------ Pizza party: Hot from the oven
    'Hot from the oven' => 'سخنة من الفرن',
    'Our oven comes to you. Dough made that morning, stretched and baked in front of your guests. Italian classics, with our own sausage and produce from the farm.'
        => 'فرننا بييجي لحد عندك. العجينة بتتعمل الصبح، وبتتفرد وتتخبز قدام ضيوفك. بيتزا إيطالي كلاسيك، بسجق من شغلنا وخضار من المزرعة.',
    'Rosemary focaccia' => 'فوكاتشا بالروزماري',
    'Baked in the pizza oven, with olive oil and sea salt.' => 'بتتخبز في فرن البيتزا، بزيت زيتون وملح بحر.',
    'Bruschetta' => 'بروسكيتا',
    'Tomato, garlic and basil on grilled bread.' => 'طماطم وتوم وريحان على عيش مشوي.',
    'Rocket salad' => 'سلطة جرجير',
    'Rocket from the farm, tomato, lemon and olive oil.' => 'جرجير من المزرعة، طماطم، لمون وزيت زيتون.',
    'Margherita' => 'مارجريتا',
    'Tomato, mozzarella, basil.' => 'طماطم، موتزاريلا، ريحان.',
    'Marinara' => 'مارينارا',
    'Tomato, garlic, oregano and olive oil. No cheese.' => 'طماطم، توم، أوريجانو وزيت زيتون. من غير جبنة.',
    'Salsiccia' => 'سالسيتشا',
    'Our own sausage, roast peppers, onion.' => 'سجق من شغلنا، فلفل مشوي، بصل.',
    'Ortolana' => 'أورتولانا',
    'Aubergine, courgette and peppers from the farm, grilled first.' => 'بدنجان وكوسة وفلفل من المزرعة، مشويين الأول.',
    'Bianca' => 'بيانكا',
    'Mozzarella, garlic, rocket and lemon. No tomato.' => 'موتزاريلا، توم، جرجير ولمون. من غير طماطم.',
    'Basterma and rocket' => 'بسطرمة وجرجير',
    'Our answer to bresaola: cured beef, mozzarella, and rocket after the oven.' => 'ردّنا على البريزاولا: بسطرمة، موتزاريلا، وجرجير بيتحط بعد الفرن.',
    'Tiramisu' => 'تيراميسو',
    'Made in our kitchen the day before, the way it should be.' => 'بيتعمل في مطبخنا قبلها بيوم، زي ما لازم يتعمل.',
    'The last pizza' => 'آخر بيتزا',
    'Cream and honey on hot dough, torn and shared.' => 'قشطة وعسل على عجينة سخنة، بتتقطّع بالإيد وتتشارك.',
    'Lemonade with mint' => 'لمون بالنعناع',
    'Lemons, mint, a little sugar.' => 'لمون، نعناع، شوية سكر.',

    // ------------------------------------------------------------ Barbecue: Around the fire
    'Around the fire' => 'حوالين النار',
    'A charcoal grill, a grill master and meat from our own butchery. Everyone ends up standing around it.'
        => 'شواية فحم، وأسطى شوي، ولحمة من جزارتنا. الكل بيلاقي نفسه واقف حواليها.',
    'Minced the same day with parsley and onion.' => 'بتتفرم في نفس اليوم مع البقدونس والبصل.',
    'Lamb chops' => 'ريش ضاني',
    'Salt, pepper, fire. Nothing else.' => 'ملح، فلفل، نار. وبس.',
    "The butcher's cut" => 'قطعية الجزار',
    'One large cut chosen by our butchery that week, grilled whole and sliced at the grill.'
        => 'قطعية كبيرة جزارتنا بتختارها في الأسبوع ده، بتتشوي حتة واحدة وبتتقطّع عند الشواية.',
    'Chicken shish' => 'شيش طاووق',
    'Our own chicken, after a night in yoghurt, lemon and garlic.' => 'فراخ من تربيتنا، بعد ليلة في الزبادي واللمون والتوم.',
    'Blistered vegetables' => 'خضار مشوي على النار',
    'Aubergine, peppers, onion and tomato, charred and dressed with lemon.' => 'بدنجان وفلفل وبصل وطماطم، مشويين ومتتبّلين باللمون.',
    'Batata in the embers' => 'بطاطا في الجمر',
    'Sweet potato cooked in the coals, split open with butter and salt.' => 'بطاطا بتستوي في الجمر، وبتتفتح بالزبدة والملح.',
    'Three bowls' => 'تلات أطباق',
    'Tahini, burnt aubergine, and a sharp tomato and garlic salsa.' => 'طحينة، بدنجان مشوي على النار، وصلصة طماطم وتوم طعمها قوي.',
    'Baladi salad' => 'سلطة بلدي',
    'Tomato, cucumber, onion and herbs, chopped small, with lemon.' => 'طماطم وخيار وبصل وخضرة، متقطّعين صغير، باللمون.',
    'House pickles' => 'مخلل البيت',
    'Carrot, turnip, lemon and chilli, pickled in our kitchen.' => 'جزر ولفت ولمون وشطة، متخلّلين في مطبخنا.',
    'Zalabia, hot' => 'زلابية سخنة',
    'Small doughnuts fried to order, with honey or sugar.' => 'بتتقلي على الطلب، بالعسل أو السكر.',
    'Guava, pomegranate, persimmon.' => 'جوافة، رمان، كاكا.',

    // ------------------------------------------------------------ Coffee break: The good break
    'The good break' => 'البريك الحلو',
    'Food people leave their desks for. Set up before the meeting, cleared before the next one.'
        => 'أكل الناس تسيب مكاتبها عشانه. بيتجهّز قبل الاجتماع، وبيتشال قبل اللي بعده.',
    'Coffee and tea' => 'قهوة وشاي',
    'Brewed on the spot.' => 'بيتعملوا في المكان.',
    'Juice of the day' => 'عصير اليوم',
    'Pressed that morning.' => 'معصور الصبح.',
    'Real hot chocolate' => 'هوت شوكليت بجد',
    'Chocolate melted into milk. No powder.' => 'شوكولاتة سايحة في اللبن. من غير بودرة.',
    'Eggs your way' => 'بيض على مزاجك',
    'For morning meetings. Cooked to order, with herbs or cheese.' => 'لاجتماعات الصبح. بيتعمل على الطلب، بالخضرة أو بالجبنة.',
    'Butter croissants' => 'كرواسون زبدة',
    'Plain or with cheese. Baked that morning.' => 'سادة أو بالجبنة. مخبوز الصبح.',
    'Small sandwiches' => 'ساندوتشات صغيرة',
    'On our own bread: roast chicken, egg and herbs, cheese and tomato.' => 'على عيش من شغلنا: فراخ مشوية، بيض وخضرة، جبنة وطماطم.',
    'Quiche of the week' => 'كيش الأسبوع',
    'Vegetables from the farm in a butter crust.' => 'خضار من المزرعة في عجينة بالزبدة.',
    'Cookies, still warm' => 'كوكيز لسه سخن',
    'Chocolate chunk, and oat and raisin. Baked that morning and served warm.' => 'بقطع الشوكولاتة، وبالشوفان والزبيب. مخبوز الصبح وبيتقدّم سخن.',
    'Sticky date cake' => 'كيكة البلح',
    'A dark, soft loaf, sliced thick.' => 'كيكة غامقة وطرية، متقطّعة حتت تخينة.',
    'Lemon loaf' => 'كيكة اللمون',
    'Sharp with lemon, with a thin glaze.' => 'لمونها واضح، وعليها طبقة سكر خفيفة.',
    'Morning pots' => 'كوبايات الصبح',
    'Yoghurt, our own granola and fruit.' => 'زبادي، جرانولا من شغلنا، وفاكهة.',
    'Fruit cups' => 'كوبايات فاكهة',
    'Cut to order.' => 'بتتقطّع على الطلب.',

    // ------------------------------------------------------------ Birthday: Make a wish
    'Make a wish' => 'اتمنّى أمنية',
    'Food children finish and parents steal. A table for the grown-ups too, and a cake made for the day.'
        => 'أكل الأطفال بيخلّصوه والأهالي بيخطفوا منه. وسفرة للكبار كمان، وتورتة معمولة لليوم ده.',
    'Mini burgers' => 'ميني برجر',
    'Beef from our butchery, soft buns baked in our kitchen.' => 'لحمة بقري من جزارتنا، وعيش طري مخبوز في مطبخنا.',
    'Crispy chicken' => 'فراخ كرسبي',
    'Our own chicken, crumbed by hand.' => 'فراخ من تربيتنا، متغطّية بالبقسماط بالإيد.',
    'Pizza squares' => 'مربعات بيتزا',
    'Tomato and cheese, straight from the oven.' => 'طماطم وجبنة، من الفرن على طول.',
    'Pasta to order' => 'مكرونة على الطلب',
    'Tomato or white sauce, cooked in the pan while they watch.' => 'بالصلصة الحمرا أو البيضا، بتتعمل في الطاسة قدامهم.',
    'Rainbow sticks' => 'صوابع قوس قزح',
    'Carrot, cucumber and peppers with tahini and labneh.' => 'جزر وخيار وفلفل مع طحينة ولبنة.',
    'Fruit sticks' => 'أسياخ فاكهة',
    'The colourful plate that empties first.' => 'الطبق الملوّن اللي بيخلص الأول.',
    'Rocket, herbs, lemon.' => 'جرجير، خضرة، لمون.',
    'Kofta rolls' => 'ساندوتشات كفتة',
    'Charcoal kofta in warm bread with tahini and pickles.' => 'كفتة على الفحم في عيش سخن مع طحينة ومخلل.',
    'With tahini and warm bread.' => 'مع طحينة وعيش سخن.',
    'The birthday cake' => 'تورتة عيد الميلاد',
    'Made to order. Tell us the name and the number.' => 'بتتعمل على الطلب. قولّنا الاسم والرقم.',
    'Fruit ice pops' => 'آيس بوب فاكهة',
    'Guava, pomegranate or karkade. Fruit, water, a little sugar.' => 'جوافة أو رمان أو كركديه. فاكهة، مية، شوية سكر.',

    // ------------------------------------------------------------ Iftar: When the sun sets
    'When the sun sets' => 'لما المغرب يدّن',
    'On the table before the call to prayer and served to share, the way an iftar should be.'
        => 'على السفرة قبل الأدان، وبيتقدّم عشان يتشارك، زي ما الفطار لازم يكون.',
    'Dates and milk' => 'بلح ولبن',
    'Waiting at every place.' => 'مستنيين كل ضيف في مكانه.',
    'Three Ramadan drinks' => 'تلات مشروبات رمضان',
    'Qamar el-din, karkade and tamarind, made in our kitchen.' => 'قمر الدين وكركديه وتمر هندي، معمولين في مطبخنا.',
    'Sambousek' => 'سمبوسك',
    'Cheese and meat, folded by hand, fried just before sunset.' => 'جبنة ولحمة، متطبّقة بالإيد، وبتتقلي قبل المغرب بشوية.',
    'Rocket, dill and coriander, baladi lemon, olive oil.' => 'جرجير وشبت وكزبرة، لمون بلدي، زيت زيتون.',
    'Lamb fattah' => 'فتة ضاني',
    'Lamb from our butchery, rice, crisp bread, garlic and vinegar.' => 'ضاني من جزارتنا، رز، عيش محمّص، توم وخل.',
    'Chicken with freekeh' => 'فراخ بالفريك',
    'Our own chicken, roasted and filled with smoked green wheat.' => 'فراخ من تربيتنا، مشوية ومحشية فريك مدخّن.',
    'Winter tagine' => 'طاجن الشتا',
    'Green peas, carrots and beef in tomato, baked in clay.' => 'بسلة وجزر ولحمة بقري في الصلصة، متسوّيين في الفخار.',
    'Mahshi' => 'محشي',
    'Vine leaves and winter cabbage, rolled by hand.' => 'ورق عنب وكرنب الشتا، ملفوفين بالإيد.',
    'Qatayef to order' => 'قطايف على الطلب',
    'Filled with nuts or cream, fried in front of you, dipped in syrup.' => 'محشية مكسرات أو قشطة، بتتقلي قدامك، وبتتغمّس في الشربات.',
    'Konafa' => 'كنافة',
    'With cream, still warm.' => 'بالقشطة، ولسه سخنة.',
    'Winter fruit' => 'فاكهة الشتا',
    'Oranges and strawberries, at their best at this time of year.' => 'برتقان وفراولة، في أحلى وقتهم في السنة.',
    'Tea with fresh mint' => 'شاي بالنعناع الأخضر',
    'And coffee, for the long evening.' => 'وقهوة، للسهرة الطويلة.',

    // ------------------------------------------------------------ Barbecue: The backyard
    'The backyard' => 'جنينة البيت',
    'American street food from our butchery: burgers, sausages and slow brisket. Paper trays, soft buns, no cutlery needed.'
        => 'أكل شارع أمريكاني من جزارتنا: برجر، سجق، وبريسكت متسوّي على مهله. أطباق ورق، عيش طري، ومن غير شوك وسكاكين.',
    'The smash burger' => 'سماش برجر',
    'Beef from our butchery, smashed on the flat-top, with cheese, pickles and our burger sauce.'
        => 'لحمة بقري من جزارتنا، مضغوطة على الصاج، مع جبنة ومخلل وصوص البرجر بتاعنا.',
    'The chicken burger' => 'برجر فراخ',
    'Our own chicken, crisp outside, with slaw in a soft bun.' => 'فراخ من تربيتنا، مقرمشة من برّه، مع كولسلو في عيش طري.',
    'Sausage in a bun' => 'سجق في عيش',
    'Our own beef sausage, grilled, with soft onions and mustard.' => 'سجق بقري من شغلنا، مشوي، مع بصل طري ومسطردة.',
    'Twelve-hour brisket' => 'بريسكت 12 ساعة',
    'Cooked low for twelve hours and sliced at the board. In a bun, or on its own.' => 'بيتسوّى على نار هادية 12 ساعة وبيتقطّع قدامك. في عيش، أو لوحده.',
    'Fries, skin on' => 'بطاطس محمّرة بقشرها',
    'Cut that morning, fried to order.' => 'متقطّعة الصبح، وبتتحمّر على الطلب.',
    'Slaw' => 'كولسلو',
    'Cabbage and carrot from the farm, in a light dressing.' => 'كرنب وجزر من المزرعة، بتتبيلة خفيفة.',
    'Corn on the cob' => 'درة مشوي',
    'Charred on the grill, with butter and salt.' => 'مشوي على الشواية، بالزبدة والملح.',
    'Pickles and sauces' => 'مخلل وصوصات',
    'House pickles, burger sauce, barbecue sauce and mustard, made in our kitchen.' => 'مخلل البيت، صوص البرجر، صوص الباربكيو، ومسطردة، كلهم معمولين في مطبخنا.',
    'Chocolate chunk. Baked that day and served warm.' => 'بقطع الشوكولاتة. مخبوز في نفس اليوم وبيتقدّم سخن.',

    // ------------------------------------------------------------ Taco bar: Build your own
    'Build your own' => 'اعمله بإيدك',
    'Warm tortillas, fillings straight from the grill and the pan, and a bar of everything to pile on top. Guests build their own, and go back for another.'
        => 'تورتيلا سخنة، حشوات من على الشواية والطاسة على طول، وبار فيه كل اللي يتحط فوقها. كل ضيف بيعمل التاكو بتاعه، وبيرجع ياخد واحد تاني.',
    'Slow beef' => 'لحمة بقري على مهلها',
    'Beef from our butchery, cooked low with cumin and chilli until it pulls apart.' => 'لحمة بقري من جزارتنا، متسوّية على نار هادية بالكمون والشطة لحد ما تتفتفت.',
    'Charcoal chicken' => 'فراخ على الفحم',
    'Our own chicken with lime and garlic, off the grill and sliced to order.' => 'فراخ من تربيتنا باللايم والتوم، من على الشواية، وبتتقطّع على الطلب.',
    'Spiced sausage' => 'سجق متبّل',
    'Our own sausage, crumbled and crisped in the pan with paprika.' => 'سجق من شغلنا، متفتفت ومحمّر في الطاسة بالبابريكا.',
    'Charred cauliflower' => 'قرنبيط مشوي',
    'From the farm, roasted with cumin and lime. For guests who skip the meat.' => 'من المزرعة، مشوي بالكمون واللايم. للي مش بياكل لحمة.',
    'Warm tortillas' => 'تورتيلا سخنة',
    'Heated on the plancha as you reach the front of the line.' => 'بتتسخّن على الصاج أول ما ييجي دورك.',
    'Fresh salsa' => 'سالسا طازة',
    'Tomato, onion, coriander and lime, chopped that day.' => 'طماطم وبصل وكزبرة ولايم، متقطّعين في نفس اليوم.',
    'Guacamole' => 'جواكامولي',
    'Mashed to order.' => 'بيتهرس على الطلب.',
    'Pink onions and slaw' => 'بصل بمبي وكولسلو',
    'Quick-pickled onions and a crisp cabbage slaw.' => 'بصل متخلّل على السريع وكولسلو كرنب مقرمش.',
    'House hot sauce' => 'شطة البيت',
    'Mild, medium, and one to be careful with.' => 'خفيفة، ووسط، وواحدة خلّي بالك منها.',
    'Corn in a cup' => 'درة في كوباية',
    'Charred corn with lime, chilli and cheese.' => 'درة مشوي باللايم والشطة والجبنة.',
    'Tortilla chips' => 'تورتيلا شيبس',
    'Fried that day, with salsa.' => 'مقلية في نفس اليوم، مع السالسا.',
    'Churros to order' => 'تشوروس على الطلب',
    'Fried in front of you, rolled in cinnamon sugar, with chocolate.' => 'بتتقلي قدامك، وبتتغطّى بالسكر والقرفة، مع شوكولاتة.',
    'Hibiscus cooler' => 'كركديه ساقع',
    'Mexico calls it jamaica, Egypt calls it karkade. Served cold with lime.' => 'في المكسيك اسمه خامايكا، وفي مصر اسمه كركديه. بيتقدّم ساقع باللايم.',

    // ------------------------------------------------------------ Halloween: The pumpkin party
    'The pumpkin party' => 'حفلة القرع',
    'A Halloween party where the colours come from the food: pumpkin, batata, karkade and beetroot. Nothing is dyed. Live stations for the children, and a table for the grown-ups too.'
        => 'حفلة هالوين ألوانها جاية من الأكل نفسه: قرع عسلي، بطاطا، كركديه وبنجر. من غير أي ألوان صناعية. أركان لايف للأطفال، وسفرة للكبار كمان.',
    'Pumpkin in a cup' => 'قرع في كوباية',
    'Roast pumpkin soup with cumin and toasted seeds, served in small cups.' => 'شوربة قرع عسلي مشوي بالكمون واللب المحمّص، في كوبايات صغيرة.',
    'Charred whole over the flame, then tahini, cumin and lemon. With warm bread.' => 'بيتشوي صحيح على النار، وبعدين طحينة وكمون ولمون. مع عيش سخن.',
    'Orange sticks' => 'صوابع برتقاني',
    'Carrot, peppers and cucumber with tahini and labneh.' => 'جزر وفلفل وخيار مع طحينة ولبنة.',
    'Make a face' => 'ارسم وش',
    'Children top their own small pizza with a face. Baked in the oven while they watch.' => 'كل طفل بيرسم وش على بيتزا صغيرة. وبتتخبز في الفرن قدامهم.',
    'Charcoal kofta in warm bread with tahini and pickles. For the grown-ups.' => 'كفتة على الفحم في عيش سخن مع طحينة ومخلل. للكبار.',
    'Pumpkin freekeh' => 'فريك بالقرع',
    'Smoked green wheat with roast pumpkin and toasted nuts. A main for guests who skip the meat.'
        => 'فريك مدخّن مع قرع عسلي مشوي ومكسرات محمّصة. طبق رئيسي للي مش بياكل لحمة.',
    "Qar' asali, warm" => 'قرع عسلي سخن',
    'The Egyptian baked pumpkin pudding, in small pots.' => 'حلو القرع العسلي المصري في الفرن، في طواجن صغيرة.',
    'The treat bar' => 'بار الحلويات',
    'Sweets made in our kitchen to fill a paper bag: sesame and peanut brittle, date and cocoa balls, popcorn.'
        => 'حلويات من شغل مطبخنا تملا بيها كيس ورق: سمسمية وفولية، كور بلح وكاكاو، فشار.',
    'Karkade pops' => 'آيس بوب كركديه',
    'Ice pops made from karkade, fruit and a little sugar.' => 'آيس بوب من الكركديه والفاكهة وشوية سكر.',
    'Red punch' => 'بانش أحمر',
    'Cold karkade with pomegranate seeds.' => 'كركديه ساقع بحبّ الرمان.',
];
